### ISSUE TITLE
Version compatilibility

### ISSUE THREAD

**Issue by 5knnbdwm** [Drunkar/blender_csv_mesh_loader#1]
Hey, in which Blender version did the script work? Tried it in v2.9 and 2.83 both of which seem to have the same problem with the API having depriciated contents used in the script

**Comment by Drunkar** [comment]
Thank you for using my addon.
I tried it in v 2.79, 2.83 and 2.90. All of them worked without problems.
Please make sure you are using the latest code.
Could you paste the error message here?

**Comment by 5knnbdwm** [comment]
mhm I think I might do something wrong then.

```
bpy.ops.object.delete(use_global=True)

Deleted 1 object(s)

Traceback (most recent call last):
  File "C:\Users\samue\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_csv_mesh_loader-master\__init__.py", line 45, in execute
    self._mcreate_mash_from_verts(obj_name, verts)
  File "C:\Users\samue\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender_csv_mesh_loader-master\__init__.py", line 60, in _mcreate_mash_from_verts
    mesh = bpy.context.object.data
AttributeError: 'NoneType' object has no attribute 'data'

location: <unknown location>:-1

bpy.ops.animation.csv_mesh_loader(filepath="C:\\Users\\samue\\OneDrive\\Documents\\xyz_1.csv")

```

**Comment by Drunkar** [comment]
Finally I faced the same issue. (I don't know why this timing. Lol)
And I updated __init__.py to resolve it. It works perfectly on my blender 2.90.
https://github.com/Drunkar/blender_csv_mesh_loader/commit/cef6abfdbab9102ab64acffd623372c9aadfcb8b
Please try it again.

**Comment by 5knnbdwm** [comment]
Yeah it works. Thanks for the quick fix 😃
